version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: berapaya
    ports:
      - "8000:8000"
    environment:
      - API_KEY=berapaya
    volumes:
      - .:/app
    restart: always
    networks:
      - shared_net

networks:
  shared_net:
    external: true